package:
  name: task-soft-s
  version: "1.0.0"

source:
  path: ../src

build:
  script: build.bat

requirements:
  build:
    - cmake
    - openssl
  run:
    - openssl

about:
  home: https://github.com/mateusz-g6/task-soft-s
  summary: "Simple hashing example with OpenSSL."
  license: MIT
